version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: __appName__
    volumes:
      - type: bind
        source: ../
        target: /workspace
    depends_on:
      - database
  database:
    image: postgres:latest
    restert: always
    volumes:
      - ./database:/docker-entrypoint.initdb.d