version: '3'
services:
  app:
    image: node-dev
    tty: true
      - type: bind
        source: ./
        target: /workspace
    depends_on:
      - database
  database:
    image: postgres:latest
    restert: always
    volumes:
      - ./database:/docker-entrypoint.initdb.d