version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: __appName__
    tty: true
    volumes:
      - type: bind
        source: ../
        target: /workspace